---
title: "Labs - Cindy"
output: html_document
---
```{r}

library(dplyr)
```

```{r}
#import Hep C patient list
hep_c_patients<-read_delim("Z:/hep_c_patients_first_encounter_date_and_first_hep_c_icd_code.csv", ",", escape_double = FALSE, trim_ws = TRUE)

hep_c_patients <- hep_c_patients[(hep_c_patients$EncountervsICD == TRUE),]

str(hep_c_patients)
```

```{r}
#filter out non hep C patients labs
hep_c_labs <- inner_join(hep_c_patients,labs)
str(hep_c_labs)
dim(hep_c_labs) #2,107,759 of 48,967,803 labs (4.3%) for 2485 patients

hep_c_labs$after_diagnosis <- ifelse(hep_c_labs$enc_dt_ds >= hep_c_labs$First_Date_with_Hep_C_ICD_code, "TRUE", "FALSE") #Evaluate whether encounter was before or after first Hep C icd code date
hep_c_labs <- hep_c_labs[(hep_c_labs$after_diagnosis=="TRUE"),]#1,588,579
dim(hep_c_labs)
```


```{r}
##CBC

#Filter on "complete blood count" 

##?????????CBC W/ DIFF & PLATELETS - What about this lab??? Same thing??  Other prc descriptions???
proc_description_CBC <- subset(hep_c_labs, proc_description =="COMPLETE BLOOD COUNT") #334,069 rows

length(unique(proc_description_CBC$PATIENT_ID))  #1749 unique patients


#Looking at components in CBC
unique(proc_description_CBC$component)  #16 unique componets

#sort by patient ID and then by date
proc_description_CBC <- proc_description_CBC[(order(proc_description_CBC$PATIENT_ID, proc_description_CBC$order_dttm_ds)),]

#reduce columns
cbc <- proc_description_CBC[c("PATIENT_ID", "ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "proc_description", "order_dttm_ds")]

#remove duplicates - each component of CBC is listed as a separate row
cbc <- cbc[!duplicated(cbc),] #27,218

##Freq of CBC labs for each patient
cbc_freq <- as.data.frame(table(cbc$PATIENT_ID))  #1749 unique patients
names(cbc_freq)[1]<-paste("PATIENT_ID")
names(cbc_freq)[2]<-paste("Num_of_CBC_Labs")

hep_c_patients <- left_join(hep_c_patients, cbc_freq)

#evaluate date difference between labs
cbc_date_diff <- cbc  %>% group_by(PATIENT_ID) %>%
  mutate(diffDate = difftime(order_dttm_ds, lag(order_dttm_ds,1), units = "days")) %>% ungroup()

cbc_date_diff$Less_than_28_days <- ifelse(cbc_date_diff$diffDate <= 28, "TRUE", "FALSE")

head(cbc_date_diff)

library(zoo) #last observation carried forward but in reserve to replace NA's in "Less_than_28_days" column
cbc_date_diff$Less_than_28_days <- na.locf(cbc_date_diff$Less_than_28_days, option = "locf", fromLast = TRUE)
head(cbc_date_diff)

## Count Freq of CBC with date difference of less than 28 days from the prior lab##
less_than_28_days <- cbc_date_diff[(cbc_date_diff$Less_than_28_days == "TRUE"),]
less_than_28_days_freq <- as.data.frame(table(less_than_28_days$PATIENT_ID)) #1434 patients
names(less_than_28_days_freq)[1]<-paste("PATIENT_ID")
names(less_than_28_days_freq)[2]<-paste("Num_of_CBC_Labs_less_than_28days")

hep_c_patients <- left_join(hep_c_patients, less_than_28_days_freq)


##Count consecutive labs that are less than 28 days apart
####Won't catch the first date of consec if consec starts after a false!!!
sumTRUE <- function(x) {x[x == "TRUE"]=sequence(with(rle(x), lengths[values == "TRUE"]));x} #helper function/ rle = run length encoding
cbc_date_diff <- less_than_28_days %>% group_by(PATIENT_ID) %>% mutate(Consec=sumTRUE(Less_than_28_days))

cbc_date_diff$Consec <- as.numeric(cbc_date_diff$Consec)

##Subsetting so it only includes patients that have at least 3 consec labs
consec_greater_than_3 <- cbc_date_diff[(cbc_date_diff$Consec == 3),]

consec_greater_than_3 <- as.data.frame(table(consec_greater_than_3$PATIENT_ID))#974 patients
names(consec_greater_than_3)[1]<-paste("PATIENT_ID")
names(consec_greater_than_3)[2]<-paste("Num_of_Consec_CBC_Labs_greater_than_3")
hep_c_patients <- left_join(hep_c_patients, consec_greater_than_3)

###look at start date and end date of consec labs
Date_consec_min <- aggregate(order_dttm_ds~PATIENT_ID, cbc_date_diff, min)
names(Date_consec_min)[2]<-paste("Min_Consec_Date")
Date_consec_max <- aggregate(order_dttm_ds~PATIENT_ID, cbc_date_diff, max)
names(Date_consec_max)[2]<-paste("Max_Consec_Date")

min_max_Date_consec <- inner_join(Date_consec_min, Date_consec_max)

#date differece start and end dates of consec
min_max_Date_consec$Total_Num_Days_between_min_max <- min_max_Date_consec$Max_Consec_Date - min_max_Date_consec$Min_Consec_Date
hep_c_patients <- left_join(hep_c_patients, min_max_Date_consec)

```

```{r}

###HIV ###

#Filter on "HIV" 

proc_description_HIV <- hep_c_labs[grep("HIV", hep_c_labs$proc_description), ] #5398
proc_description_HIC <- proc_description_HIV[(order(proc_description_HIV$PATIENT_ID, proc_description_HIV$order_dttm_ds)),]

length(unique(proc_description_HIV$PATIENT_ID))  #965 unique patients

HIV <- proc_description_HIV[c("PATIENT_ID", "ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "proc_description", "order_dttm_ds")]
HIV <- HIV[!duplicated(HIV),] #36,009

##Evaluating whe HIV test was compared to CBC labs
HIV <- left_join(HIV, min_max_Date_consec)
HIV$HIV_First_CBC_Date_diff <- (HIV$order_dttm_ds - HIV$Min_Consec_Date)

HIV$During_CBC_Consec <- ifelse(HIV$order_dttm_ds >= HIV$Min_Consec_Date & HIV$order_dttm_ds <= HIV$Max_Consec_Date, "TRUE", "FALSE")

##  Freq of HIV labs
HIV_freq <- as.data.frame(table(HIV$PATIENT_ID))
names(HIV_freq)[1]<-paste("PATIENT_ID")
names(HIV_freq)[2]<-paste("Num_of_HIV_Labs")

hep_c_patients <- left_join(hep_c_patients, HIV_freq)


##  Freq of HIV labs that occurred during CBC conse
HIV_tests_during_CBC_consec <- subset(HIV, During_CBC_Consec == "TRUE")
HIV_freq_CBC_consec <- as.data.frame(table(HIV_tests_during_CBC_consec$PATIENT_ID))
names(HIV_freq_CBC_consec)[1]<-paste("PATIENT_ID")
names(HIV_freq_CBC_consec)[2]<-paste("Num_of_HIV_Labs_during_CBC_consec")

hep_c_patients <- left_join(hep_c_patients, HIV_freq_CBC_consec)
```

```{r}
### HEP B ###

#Filter on "Hep B"
component_Hep_B <- hep_c_labs[grep("HEPATITIS B", hep_c_labs$component), ] #3046
component_Hep_B <- component_Hep_B[(order(component_Hep_B$PATIENT_ID, component_Hep_B$order_dttm_ds)),]

length(unique(component_Hep_B$PATIENT_ID))  #886 unique patients

##Evaluating whether Hep B test was compared to CBC labs
component_Hep_B <- left_join(component_Hep_B, min_max_Date_consec)
component_Hep_B$Hep_B_First_CBC_Date_diff <- (component_Hep_B$order_dttm_ds - component_Hep_B$Min_Consec_Date)

component_Hep_B$During_CBC_Consec <- ifelse(component_Hep_B$order_dttm_ds >= component_Hep_B$Min_Consec_Date & component_Hep_B$order_dttm_ds <= component_Hep_B$Max_Consec_Date, "TRUE", "FALSE")

##freq of Hep B labs
Hep_B_freq <- as.data.frame(table(component_Hep_B$PATIENT_ID))
names(Hep_B_freq)[1]<-paste("PATIENT_ID")
names(Hep_B_freq)[2]<-paste("Num_of_Hep_B_Labs")

hep_c_patients <- left_join(hep_c_patients, Hep_B_freq)

##  Freq of HIV labs that occurred during CBC conse
Hep_B_tests_during_CBC_consec <- subset(component_Hep_B, During_CBC_Consec == "TRUE")
Hep_B_freq_CBC_consec <- as.data.frame(table(Hep_B_tests_during_CBC_consec$PATIENT_ID))
names(Hep_B_freq_CBC_consec)[1]<-paste("PATIENT_ID")
names(Hep_B_freq_CBC_consec)[2]<-paste("Num_of_Hep_B_Labs_during_CBC_consec")

hep_c_patients <- left_join(hep_c_patients, Hep_B_freq_CBC_consec)

```

```{r}

##had at least one CBC lab, HIV lab, and Hep B lab
treatment_patients <- subset(hep_c_patients, !is.na(Num_of_CBC_Labs) &
                               !is.na(Num_of_HIV_Labs) &
                               !is.na(Num_of_Hep_B_Labs))  #478 unique patients

select_treatment_patients <- subset(hep_c_patients, !is.na(Num_of_Consec_CBC_Labs_greater_than_3) &
                               !is.na(Num_of_HIV_Labs_during_CBC_consec) &
                               !is.na(Num_of_Hep_B_Labs_during_CBC_consec))  #216 unique patients


```


```{r}
#Look at meds for 892 patients meeting 3 consec criteria

names(meds_inpt)
names(meds_outpt)
reduced_meds_inpt2 <- meds_inpt[c(1, 7, 8, 9, 10, 11, 12, 13)]
reduced_meds_outpt2 <- meds_outpt[c(1, 6, 7, 8, 9, 10, 11, 12)]

#bind inpt and outpt
reduced_meds <- rbind(reduced_meds_inpt2, reduced_meds_outpt2)
reduced_meds$Patient_ID<-as.factor(reduced_meds$Patient_ID) 
reduced_meds$Patient_ID<-str_pad(reduced_meds$Patient_ID, 10, pad = "0")
colnames(reduced_meds)[1] <- "PATIENT_ID"

#subset meds by the 892 patients meeting 3 consec criteria
meds_3consec <- subset(reduced_meds, reduced_meds$PATIENT_ID %in% consec_greater_than_3$PATIENT_ID)

#need to determine if meds_3consec$Order_DT_DS is later than Patient_ID's FIRST CBC date
meds_3consec <- left_join(meds_3consec,hep_c_patients$Min_Consec_Date)


#look at unique med combos for the 892 patients
meds_3consec_uniques <- unique(meds_3consec[c("Thera_class_c","Thera_class","Pharm_class_c","Pharm_class","Pharm_subclass_c","Pharm_subclass")])



```


########## STOP HERE ########


```{r}
### Hepatic Function Panel ###

#Filter on "Hepatic Function Panel"
proc_description_Hep_panel <- hep_c_labs[grep("HEPATIC FUNCTION PANEL", hep_c_labs$proc_description), ] #68,472

length(unique(proc_description_Hep_panel$PATIENT_ID))  #1,146 unique patients

proc_description_Hep_panel$component <- droplevels(proc_description_Hep_panel$component)
table(proc_description_Hep_panel$component)
                #ALBUMIN    ALKALINE PHOSPHATASE              ALT (SGPT)              AST (SGOT)   BILIRUBIN, CONJUGATED        BILIRUBIN, TOTAL BILIRUBIN, UNCONJUGATED           TOTAL PROTEIN 
                   #8559                    8559                    8559                    8559                    8559                    8559                    8559                    8559 

Hep_panel_freq <- as.data.frame(table(proc_description_Hep_panel$PATIENT_ID))
names(Hep_panel_freq)[1]<-paste("PATIENT_ID")
names(Hep_panel_freq)[2]<-paste("Num_of_Hep_panels")

subset(proc_description_Hep_panel, component == "AST (SGOT)")

```

```{r}
### Renal Function Panel ###

#Filter on "Renal Function Panel"
proc_description_Renal_panel <- hep_c_labs[grep("Renal", hep_c_labs$proc_description), ] #68,472

length(unique(proc_description_Renal_panel$PATIENT_ID))  #1,146 unique patients


```

```{r}

hep_c_patients$date_diff_EncvsICD <- hep_c_patients$First_Date_with_Hep_C_ICD_code - hep_c_patients$First_Encounter_Date
mean(hep_c_patients$date_diff_EncvsICD)
min(hep_c_patients$date_diff_EncvsICD)
max(hep_c_patients$date_diff_EncvsICD)

hep_c_patients[order(-hep_c_patients$date_diff_EncvsICD),]

hep_c_patients_labs <- subset(hep_c_patients, !is.na(First_Hep_C_Lab_Date))

hep_c_patients_labs$ICDvsLab <- ifelse(hep_c_patients_labs$First_Date_with_Hep_C_ICD_code ==  hep_c_patients_labs$First_Hep_C_Lab_Date, "Same",
                                ifelse(hep_c_patients_labs$First_Date_with_Hep_C_ICD_code < hep_c_patients_labs$First_Hep_C_Lab_Date, 
"First ICD Before First Lab", "First ICD After First Lab"))

table(hep_c_patients_labs$ICDvsLab)

subset(hep_c_patients_labs, ICDvsLab == "First ICD Before First Lab")#176
subset(hep_c_patients_labs, ICDvsLab == "Same") #304
first_icd_after <- subset(hep_c_patients_labs, ICDvsLab == "First ICD After First Lab")#305
nrow(subset(first_icd_after, First_Date_with_Hep_C_ICD_code > "2014-01-01")) #205
first_icd_after_labs <- labs[labs$PATIENT_ID %in% first_icd_after$PATIENT_ID,]

```

```{r}

###Tests with  Hep C ##
proc_description_hep <- hep_c_labs[grep("HEP", hep_c_labs$proc_description),] #105,827 - looks like 
unique(proc_description_hep$proc_description)

proc_description_HEPATITIS_C <- hep_c_labs[grep("HEPATITIS C", hep_c_labs$proc_description),] #2131 for all 3705 patienst- looks like 
#codes = 1145, 5584
unique(proc_description_HEPATITIS_C$component_id)


component_HEP <- hep_c_labs[grep("HEP", hep_c_labs$component),] #11,862 

component_HEPATITIS_C <- hep_c_labs[grep("HEPATITIS C", hep_c_labs$component),] #3549 rows for 3705 patients
#Hep Antibody, Hep C Virus AB, Hep Panel, ACUTE
#1147 unique Ptient ID's out of 3705 patients

component_HEPATITIS_C_table <- as.data.frame(table(component_HEPATITIS_C$PATIENT_ID))
component_HEPATITIS_C_table[order(-component_HEPATITIS_C_table$Freq),]
component_HEPATITIS_C_table
names(component_HEPATITIS_C_table)[1]<-paste("PATIENT_ID")
names(component_HEPATITIS_C_table)[2]<-paste("Num_of_Hep_C_Labs")
table(component_HEPATITIS_C_table$Num_of_Hep_C_Labs)



component_HEPATITIS_C[(order(component_HEPATITIS_C$PATIENT_ID, component_HEPATITIS_C$order_dttm_ds)),]
unique(component_HEPATITIS_C$order_value)
component_HEPATITIS_C$proc_description <- droplevels(component_HEPATITIS_C$proc_description)


hep_c_patients <- left_join(hep_c_patients, component_HEPATITIS_C_table)
nrow(subset(hep_c_patients, date_diff_EncvsICD == 0 & is.na(Num_of_Hep_C_Labs)))
nrow(subset(hep_c_patients, date_diff_EncvsICD > 0 & is.na(Num_of_Hep_C_Labs)))

nrow(subset(hep_c_patients, date_diff_EncvsICD == 0 & is.na(Num_of_Hep_C_Labs))) / nrow(subset(hep_c_patients, date_diff_EncvsICD == 0))
nrow(subset(hep_c_patients, date_diff_EncvsICD > 0 & is.na(Num_of_Hep_C_Labs)))
nrow(subset(hep_c_patients, date_diff_EncvsICD > 0 & is.na(Num_of_Hep_C_Labs)))
nrow(subset(hep_c_patients, date_diff_EncvsICD > 0 & is.na(Num_of_Hep_C_Labs))) / nrow(subset(hep_c_patients, date_diff_EncvsICD > 0))

##first Hep C test added to patient list
hep_c_labs_first_date <- aggregate(enc_dt_ds~PATIENT_ID,  data = component_HEPATITIS_C, min) 
names(hep_c_labs_first_date)[names(hep_c_labs_first_date) == "enc_dt_ds"] <- "First_Hep_C_Lab_Date" #785 patients

hep_c_patients <- left_join(hep_c_patients, hep_c_labs_first_date)
sum(is.na(hep_c_patients$First_Hep_C_Lab_Date)) #2920

hep_c_patients$date_diff_EncvsHepCLab <- hep_c_patients$First_Hep_C_Lab_Date - hep_c_patients$First_Encounter_Date

hep_c_patients[order(-hep_c_patients$Num_of_Hep_C_Labs),]

subset(hep_c_patients, Num_of_Hep_C_Labs == 4)
```


-------------------------  New Code  ------------------------
```{r}
######  Meds and notes from Tanmayi  #########


###  Hep C meds  #####
#42 ANTIVIRALS 1337 HEP C VIRUS-NS5B POLYMERASE AND NS5A INHIB. COMBO.2690 Hepatitis C - NS5B Polymerase and NS5A Inhibitor Combinations
#42 ANTIVIRALS 637 HEPATITIS C TREATMENT AGENTS 1821 Hepatitis C - Nucleoside Analogs
##42 ANTIVIRALS 637 HEPATITIS C TREATMENT AGENTS 1146 Hepatitis C - Interferons (patients on HCV treatment no longer receive medications in Pharm Sub Class ID #1146 (Interferons). If a patient who  has been treated in the last 2 years shows up with just an Interferon, they are likely using it for non-HCV indications)  CK- but we don't know what is in "the last 2 years" because of date shifting
#42 ANTIVIRALS 1307 HEP C VIRUS,NUCLEOTIDE ANALOG NS5B POLYMERASE INH 2622 Hepatitis C - Nucleos(t)ide Analog NS5B Polymerase Inhibitors
#42 ANTIVIRALS 1193 HEPATITIS C VIRUS NS3/4A SERINE PROTEASE INHIB. 2466 Hepatitis C - NS3/4A Serine Protease Inhibitors
#42 ANTIVIRALS 1342 HEPATITIS C VIRUS - NS5A, NS3/4A, NS5B INHIB CMB.2700 Hepatitis C- NS5A, NS3/4A  Protease and Non-Nucleo.NS5B Poly Inh. Comb

###  Meds taken with Hep C meds  ####
#Patients who are treated for HCV often require only the HCV medication for their treatment. The only medication that is sometimes used with the HCV medications listed below is ribavirin.
#37	VITAMINS	69	VITAMIN B2 PREPARATIONS	555	Vitamins - B-2, Riboflavin and Derivatives

###reduce columns of med tables and combine into one
names(meds)
reduced_meds_inpt <- meds_inpt[c(1:4, 6:22, 27)]
names(reduced_meds_inpt)[4]<-paste("Enc_ADM_DT_DS")
reduced_meds_inpt$Enc_Type <- "I"  #identify which table the med order comes from
reduced_meds_outpt <- meds_outpt[-c(17:19)]
names(reduced_meds_outpt)[4]<-paste("Enc_ADM_DT_DS")
reduced_meds_outpt$Enc_Type <- "O" #identify which table the med order comes from


meds <- rbind(reduced_meds_inpt, reduced_meds_outpt) #23,252,604 rows


#combine with Hep C patients
hep_c_meds <- inner_join(hep_c_patients, meds)
dim(hep_c_meds) #1109296
head(hep_c_meds)
length(unique(hep_c_meds$PATIENT_ID))#2454


##Filter on Hep C meds only
hep_c_pts_hep_c_meds <- hep_c_meds %>%
  filter(Pharm_subclass_c == 2690 | 
        Pharm_subclass_c == 1821|
        #Pharm_subclass_c == 1146 |
        Pharm_subclass_c == 2622 |
        Pharm_subclass_c == 2466 |
        Pharm_subclass_c == 2700) #1,133
dim(hep_c_pts_hep_c_meds)
length(unique(hep_c_pts_hep_c_meds$PATIENT_ID)) #383 unique patients
hep_c_pts_hep_c_meds$Pharm_subclass_c <- droplevels(hep_c_pts_hep_c_meds$Pharm_subclass_c)
hep_c_pts_hep_c_meds$Pharm_subclass <- droplevels(hep_c_pts_hep_c_meds$Pharm_subclass)
as.data.frame(table(hep_c_pts_hep_c_meds$Pharm_subclass_c))


```
```{r}
#############  Exploratory - Hep C meds #####

##Unique patient ID
unique_hep_c_pt_id_hep_c_meds <- hep_c_pts_hep_c_meds %>%
    distinct(PATIENT_ID) %>%
  select(PATIENT_ID) #383 unique patients

#Med order Freq per patient
med_freq_per_pt <- as.data.frame(table(hep_c_pts_hep_c_meds$PATIENT_ID))
mean(med_freq_per_pt$Freq) #2.958225
min(med_freq_per_pt$Freq) #1
max(med_freq_per_pt$Freq) #121
table(med_freq_per_pt$Freq)

hist(med_freq_per_pt$Freq)
med_freq_per_pt[order(-med_freq_per_pt$Freq),]

inpt_hep_c_meds <- subset(hep_c_pts_hep_c_meds, Enc_Type == "I")
unique_ids_inpt_hep_c_meds <- as.data.frame(unique(inpt_hep_c_meds$PATIENT_ID)) #40
names(unique_ids_inpt_hep_c_meds)[1]<-paste("PATIENT_ID")
outpt_hep_c_meds <- subset(hep_c_pts_hep_c_meds, Enc_Type == "O")
unique_ids_outpt_hep_c_meds <- as.data.frame(unique(outpt_hep_c_meds$PATIENT_ID)) #375
names(unique_ids_outpt_hep_c_meds)[1]<-paste("PATIENT_ID")

inner_join(unique_ids_inpt_hep_c_meds, unique_ids_outpt_hep_c_meds)

#HEP C         Order Date
#2013-02-03	   2013-12-07	

subset(encounters, PATIENT_ID == "0000079153" & Enc_DT_DS == "2012-07-19")
subset(rna, PATIENT_ID == "0001131794")
subset(hep_c_pts_hep_c_meds, PATIENT_ID == "0001706700")
```

```{r}
##  Look at dates for orders  

hep_c_pts_hep_c_meds[duplicated(hep_c_pts_hep_c_meds),]

#Find Freq order date for Hep C
Med_Freq_Orders <- hep_c_pts_hep_c_meds %>%
   group_by(PATIENT_ID) %>%
  summarize(Med_Freq_Orders =n())

#Find Freq order by EncType date for Hep C
Med_Freq_Orders_by_EncType <- hep_c_pts_hep_c_meds %>%
   group_by(PATIENT_ID, Enc_Type) %>%
  summarize(Med_Freq_Orders =n())

Med_Freq_Orders_by_InptEncType <- subset(Med_Freq_Orders_by_EncType, Enc_Type == "I")
names(Med_Freq_Orders_by_InptEncType)[3]<-paste("Med_Freq_InptOrders")
Med_Freq_Orders_by_InptEncType <- Med_Freq_Orders_by_InptEncType[c(1,3)]
Med_Freq_Orders_by_OutptEncType <- subset(Med_Freq_Orders_by_EncType, Enc_Type == "O")
names(Med_Freq_Orders_by_OutptEncType)[3]<-paste("Med_Freq_OutptOrders")
Med_Freq_Orders_by_OutptEncType <- Med_Freq_Orders_by_OutptEncType[c(1,3)]

#Find First and Last order date for Hep C
Med_First_Order_Date <- hep_c_pts_hep_c_meds %>%
  group_by(PATIENT_ID) %>%
  summarize(Med_First_Order_Date = min(Order_DT_DS))

Med_Last_Order_Date <- hep_c_pts_hep_c_meds %>%
  group_by(PATIENT_ID) %>%
  summarize(Med_Last_Order_Date = max(Order_DT_DS))

med_variable <- left_join(Med_Freq_Orders, Med_Freq_Orders_by_InptEncType)
med_variable <- left_join(med_variable, Med_Freq_Orders_by_OutptEncType)
med_variable <- left_join(med_variable, Med_First_Order_Date)
med_variable <- left_join(med_variable, Med_Last_Order_Date)
pts_med_variable <- inner_join(hep_c_patients, med_variable)

pts_med_variable[is.na(pts_med_variable)] <- 0

##Look at date difference

pts_med_variable %>%
  select(First_Date_with_Hep_C_ICD_code, Med_Last_Order_Date, Med_First_Order_Date)

#Time difference (in days) between first Hep C icd code and hep c med order date
pts_med_variable$Date_Diff_Diagnosis_Med <- pts_med_variable$Med_First_Order_Date - pts_med_variable$First_Date_with_Hep_C_ICD_code
mean(pts_med_variable$Date_Diff_Diagnosis_Med) #650.705 days
min(pts_med_variable$Date_Diff_Diagnosis_Med) #-495 days
max(pts_med_variable$Date_Diff_Diagnosis_Med) #1770 days

pts_med_variable_id <- pts_med_variable %>%
  distinct(PATIENT_ID) %>%
  select(PATIENT_ID) #383

```

```{r}

###All lab
rna_labs_table <- labs[grep("RNA", labs$proc_description), ]  #2016
rna_labs_table$proc_description <- droplevels(rna_labs_table$proc_description)
table(rna_labs_table$proc_description)

########  RNA Lab Data  ########

#Number of unique patients in RNA dataset
rna_pt_id <- rna %>%
  distinct(PATIENT_ID) %>%
  select(PATIENT_ID) #2783

#join hep c patients and rna lab table
hep_c_rna <- inner_join(hep_c_patients, rna)
dim(hep_c_rna)#914
length(unique(hep_c_rna$PATIENT_ID)) #484
hep_c_rna_pt_id <- hep_c_rna %>%
  distinct(PATIENT_ID) %>%
  select(PATIENT_ID) #484

inner_join(hep_c_rna_pt_id, pts_med_variable_id)  #193

#looking at differnt procedure data
proc_types <- hep_c_rna[c("proc_desc", "component_id", "component_name")]
proc_types <- proc_types[!duplicated(proc_types),]
write.csv2(proc_types, )
proc_types[!duplicated(proc_types$proc_code),]
proc_types[!duplicated(proc_types$component_id),]
proc_types[!duplicated(proc_types$component_name),]

#subset RNA tests
rna_tests_1 <- hep_c_rna[grep("RNA", hep_c_rna$proc_desc), ]  #430
length(unique(rna_tests_1$PATIENT_ID)) #98
rna_lab_only_pt_id <- rna_tests_1 %>%
  distinct(PATIENT_ID) %>%
  select(PATIENT_ID) #98
inner_join(rna_lab_only_pt_id, pts_med_variable)
```

```{r}
#Find Freq of all RNA labs for Hep C
Freq_AllLabs <- hep_c_rna %>%
   group_by(PATIENT_ID) %>%
  summarize(Freq_AllLabs =n())

#Find First and Last order date for Hep C
First_AllLabs_Order_Date <- hep_c_rna %>%
  group_by(PATIENT_ID) %>%
  summarize(First_AllLabs_Order_Date = min(order_dttm_ds))

Last_AllLabs_Order_Date <- hep_c_rna %>%
  group_by(PATIENT_ID) %>%
  summarize(Last_AllLabs_Order_Date = max(order_dttm_ds))

#Find Freq of RNA labs for Hep C
Freq_RNALabs <- rna_tests_1 %>%
   group_by(PATIENT_ID) %>%
  summarize(Freq_RNALabs =n())

First_RNALabs_Order_Date <- rna_tests_1 %>%
  group_by(PATIENT_ID) %>%
  summarize(First_RNALabs_Order_Date = min(order_dttm_ds))

Last_RNALabs_Order_Date <- rna_tests_1 %>%
  group_by(PATIENT_ID) %>%
  summarize(Last_RNALabs_Order_Date = max(order_dttm_ds))


lab_variable <- left_join(Freq_AllLabs, First_AllLabs_Order_Date)
lab_variable <- left_join(lab_variable, Last_AllLabs_Order_Date)
lab_variable <- left_join(lab_variable, Freq_RNALabs)


lab_variable <- left_join(lab_variable, First_RNALabs_Order_Date)
lab_variable <- left_join(lab_variable, Last_RNALabs_Order_Date)
pts_lab_variable <- inner_join(hep_c_patients, lab_variable)

pts_lab_variable$Date_Diff_Diag_AllLab <- pts_lab_variable$First_AllLabs_Order_Date - pts_lab_variable$First_Date_with_Hep_C_ICD_code ########  why is there such a difference between diagnosis and treatment????? is this normal???????
mean(pts_lab_variable$Date_Diff_Diag_AllLab) # 399.8636 days
min(pts_lab_variable$Date_Diff_Diag_AllLab) #-882 days
max(pts_lab_variable$Date_Diff_Diag_AllLab) #1717 days

pts_lab_variable$Date_Diff_Diag_RNALab <- pts_lab_variable$First_RNALabs_Order_Date - pts_lab_variable$First_Date_with_Hep_C_ICD_code ########  why is there such a difference between diagnosis and treatment????? is this normal???????
mean(pts_lab_variable$Date_Diff_Diag_RNALab[!is.na(pts_lab_variable$Date_Diff_Diag_RNALab)]) # 473.2755 days
min(pts_lab_variable$Date_Diff_Diag_RNALab[!is.na(pts_lab_variable$Date_Diff_Diag_RNALab)]) #-882 days
max(pts_lab_variable$Date_Diff_Diag_RNALab[!is.na(pts_lab_variable$Date_Diff_Diag_RNALab)]) #1667 days

```

```{r}
###Combine med and RNA lab data 

pts_lab_meds_variable <- inner_join(pts_lab_variable, pts_med_variable)

sum(is.na(pts_lab_meds_variable$Freq_RNALabs))#141

pts_lab_meds_variable$Date_Diff_Med_AllLab <- pts_lab_meds_variable$First_AllLabs_Order_Date - pts_lab_meds_variable$Med_First_Order_Date
mean(pts_lab_meds_variable$Date_Diff_Med_AllLab) # -40.31088 days  (postive lab was first)
min(pts_lab_meds_variable$Date_Diff_Med_AllLab) # -1340 days
max(pts_lab_meds_variable$Date_Diff_Med_AllLab) #1288 days

pts_lab_meds_variable$Date_Diff_Med_RNALab <- pts_lab_meds_variable$First_RNALabs_Order_Date - pts_lab_meds_variable$Med_First_Order_Date
mean(pts_lab_meds_variable$Date_Diff_Med_RNALab[!is.na(pts_lab_meds_variable$Date_Diff_Med_RNALab)]) # -46.01923 days
min(pts_lab_meds_variable$Date_Diff_Med_RNALab[!is.na(pts_lab_meds_variable$Date_Diff_Med_RNALab)]) #-1340 days
max(pts_lab_meds_variable$Date_Diff_Med_RNALab[!is.na(pts_lab_meds_variable$Date_Diff_Med_RNALab)]) #1018 days

```

```{r}
##Combine original lab data with med/lab variables
pts_lab_meds_labs <- inner_join(pts_lab_meds_variable, rna)

#sort by patient ID and then by date
pts_lab_meds_labs_2 <- pts_lab_meds_labs[(order(rna_tests_1$PATIENT_ID, rna_tests_1$order_dttm_ds)),]

#Calcuate date difference between lab order date and first med order date
pts_lab_meds_labs_2$Date_Diff_LabOrder_FirstMedOrder <- pts_lab_meds_labs_2$order_dttm_ds - pts_lab_meds_labs_2$Med_First_Order_Date

pts_lab_meds_labs_3 %>%
  select(PATIENT_ID, First_Order_Date, order_dttm_ds, Date_Diff_LabOrder_FirstMedOrder)

#Subsetting lab oversations to ones that occurred 30 days prior or after first med treatment order date
pts_lab_meds_labs_3 <- subset(pts_lab_meds_labs_2, Date_Diff_LabOrder_FirstMedOrder > 0)
length(unique(pts_lab_meds_labs_3$PATIENT_ID)) #102

#Find Freq of labs by patientID for labs that occurred 30 days prior or after first med treatment order date
Freq_AllLabs_AfterMedOrder <- pts_lab_meds_labs_3 %>%
   group_by(PATIENT_ID) %>%
  summarize(Freq_AllLabs_AfterMedOrder =n())

mean(Freq_AllLabs_AfterMedOrder$Freq_AllLabs_AfterMedOrder)
hist(Freq_AllLabs_AfterMedOrder$Freq_AllLabs_AfterMedOrder)
nrow(subset(Freq_AllLabs_AfterMedOrder,Freq_AllLabs_AfterMedOrder >4))
table(Freq_AllLabs_AfterMedOrder$Freq_AllLabs_AfterMedOrder)

pts_lab_meds_labs_4 <- inner_join(pts_lab_meds_labs_3, Freq_AllLabs_AfterMedOrder)


#evaluate date difference between lab observation
pts_lab_meds_labs_5 <- pts_lab_meds_labs_4  %>% group_by(PATIENT_ID) %>%
  mutate(diffDate = difftime(order_dttm_ds, lag(order_dttm_ds,1), units = "days")) %>% ungroup()

pts_lab_meds_labs_5 %>%
  filter(Freq_AllLabs_AfterMedOrder == 6) %>%
  select(PATIENT_ID, Freq_Orders,Date_Diff_LabOrder_FirstMedOrder, diffDate, Freq_AllLabs_AfterMedOrder)


rna_tests_date_diff$thirty_day_window <- ifelse(rna_tests_date_diff$diffDate >= 21 & rna_tests_date_diff$diffDate <= 35, "TRUE", "FALSE")

library(zoo) #last observation carried forward but in reserve to replace NA's in "thirty_day_window" column
rna_tests_date_diff$thirty_day_window <- na.locf(rna_tests_date_diff$thirty_day_window, option = "locf", fromLast = TRUE)
head(rna_tests_date_diff)
```

